Allow to setup package with older python3
For example with Python 3.7 without this patch its failing with:

```
      File "/tmp/pip-req-build-mkwq4yyi/setup.py", line 4, in <module>
        from importlib.metadata import version, PackageNotFoundError
    ModuleNotFoundError: No module named 'importlib.metadata'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
/tmp/pip-req-build-mkwq4yyi/
```

This also remove unused import `os` and `re`